IF OBJECT_ID('dbo.TBI_GAME') IS NOT NULL
    DROP TABLE dbo.TBI_GAME
GO

CREATE TABLE TBI_GAME (
    ID_GAME INTEGER PRIMARY KEY,
    EVENT_GAME VARCHAR(255),
    SITE_GAME VARCHAR(255),
    DATE_GAME VARCHAR(255),
    ROUND_GAME VARCHAR(255) NOT NULL,
    WHITE_PLAYER VARCHAR(255) NOT NULL,
    BLACK_PLAYER VARCHAR(255) NOT NULL,
    RESULT VARCHAR(255),
    WHITE_ELO VARCHAR(255),
    BLACK_ELO VARCHAR(255),
    ECO VARCHAR(255),
    DATE_MODIF DATETIME,
    GAME_CMD VARCHAR(255)
);

EXEC ADD_EXPED_VERSION '1.0.0'