SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [dbo].[VERSION];

GO

CREATE TABLE [dbo].[VERSION](
	[VERSION_OLD] [VARCHAR](10) NULL,
	[VERSION_NOW] [VARCHAR](10) NULL,
	[DATE_UPDATE] [DATETIME] NULL,
	[LAST_LINE] [INT] NULL,
	[LOG_UPDATE] [TEXT] NULL,
	[SYSTEM_VERSION] [VARCHAR](50) NOT NULL,
CONSTRAINT [PK_VERSION] PRIMARY KEY CLUSTERED (
    [SYSTEM_VERSION] ASC
) WITH ( 
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

IF OBJECT_ID('dbo.ADD_EXPED_VERSION') IS NOT NULL
    DROP PROCEDURE dbo.ADD_EXPED_VERSION
GO

CREATE PROCEDURE dbo.ADD_EXPED_VERSION
(
	@version VARCHAR(10)
)AS
BEGIN
	declare @verMajor char(1)
	set @verMajor = SUBSTRING(@version,1,1)
	declare @system varchar(10)
	set @system = 'CHESS_' + @verMajor
	IF EXISTS (SELECT VERSION_NOW FROM dbo.VERSION  WHERE SYSTEM_VERSION = @system)
		UPDATE dbo.VERSION
		SET VERSION_OLD = VERSION_NOW, VERSION_NOW = @version, DATE_UPDATE = GETDATE()
		WHERE SYSTEM_VERSION = @system
	ELSE
		INSERT INTO dbo.VERSION (VERSION_OLD, VERSION_NOW, DATE_UPDATE, SYSTEM_VERSION)
		VALUES ('000000', @version, GETDATE(), @system)
END

GO

EXEC ADD_EXPED_VERSION '1.0.0'